name: "my-mcp"
version: 0.0.1
inputs:
  - topic: coding
    paths: [ "docs/coding" ]
    rank: 10
  - topic: documenting
    paths: [ "docs/documenting" ]
    rank: 10
  - topic: testing
    paths: [ "docs/testing" ]
    rank: 10
output: "database"
batch_size: 64
openai_host: "https://api.openai.com/v1"
openai_key: "sk-xxx"
embedding_model: "local"
budgets:
  max_chunk_tokens: 400
  overlap_tokens: 32
